apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: kunde-portal-beta
  name: kunde-portal-beta
spec:
  ports:
  - name: "80"
    port: 80
  selector:
    io.kompose.service: kunde-portal-beta
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-kunde-portal
data:
  nginx.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;

      server_name kunde-beta.felleskomponent.no;

      location / {
          proxy_pass http://localhost:8000;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }

      location /api/ {
          proxy_pass http://localhost:8080;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }

    location /actuator/ {
        proxy_pass http://localhost:8080;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }

      location /api/tests/links/ {
          proxy_pass http://localhost:8081;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }

      location /api/tests/ {
          proxy_pass http://localhost:8082;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }

      location /tickets {
           proxy_pass http://localhost:8083;
           proxy_set_header Connection '';
           proxy_http_version 1.1;
           chunked_transfer_encoding off;
           proxy_buffering off;
           proxy_cache off;
       }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kunde-portal-beta
  name: kunde-portal-beta
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: kunde-portal-beta
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        io.kompose.service: kunde-portal-beta
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      restartPolicy: Always
      volumes:
        - name: nginx-kunde-portal
          configMap:
            name: nginx-kunde-portal
      containers:
      - name: kunde-portal-beta
        image: fintlabsacr.azurecr.io/kunde-portal:build.${BUILD_NUMBER}_${GIT_COMMIT}
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
          - secretRef:
              name: fint-portal-user
        env:
        - name: TZ
          value: Europe/Oslo
        - name: fint.client-config.test-service-base-url
          value: ""
        - name: fint.client-config.linkwalker-base-url
          value: ""
        - name: logging.level.no.fint.portal.security
          value: debug
        - name: logging.level.org.springframework.security
          value: debug
        - name: fint.ldap.access.template-base
          value: ou=access,o=fint
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "250m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            httpHeaders:
              - name: x-nin
                value: '0'
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: nginx
        image: nginx:1.15.10
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        env:
          - name: TZ
            value: Europe/Oslo
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-kunde-portal
      - name: frontend
        image: fintlabsacr.azurecr.io/kunde-portal-frontend:latest
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
          - containerPort: 8000
        env:
          - name: TZ
            value: Europe/Oslo
      - name: test-runner
        image: fintlabsacr.azurecr.io/test-runner:PR-6.1
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "250m"
            memory: "1Gi"
        ports:
          - containerPort: 8082
        envFrom:
          - secretRef:
              name: fint-portal-user
        env:
          - name: server.port
            value: "8082"
      - name: link-walker
        image: fintlabsacr.azurecr.io/link-walker:PR-16.5
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "250m"
            memory: "3Gi"
        ports:
          - containerPort: 8081
        envFrom:
          - secretRef:
              name: fint-portal-user
        env:
          - name: TZ
            value: Europe/Oslo
          - name: JAVA_TOOL_OPTIONS
            value: '-XX:+ExitOnOutOfMemoryError -Xmx3G -verbose:gc'
          - name: server.port
            value: "8081"
          - name: fint.rest-template.provider
            value: portal-api
      - name: zendesk-integration
        image: fintlabsacr.azurecr.io/zendesk-integration:build.17
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "250m"
            memory: "1Gi"
        ports:
          - containerPort: 8083
        envFrom:
          - secretRef:
              name: fint-portal-user
        env:
          - name: logging.level.no.fint.provisioning.TicketSynchronizingService
            value: debug
          - name: fint.webclient.connection-provider.type
            value: NEW
          - name: fint.zendesk.timeout
            value: PT10S
          - name: TZ
            value: Europe/Oslo
          - name: fint.zendesk.prov.user.queuing.delay
            value: "600000"
          - name: fint.zendesk.users.enabled
            value: "true"
          - name: server.port
            value: "8083"
          - name: fint.zendesk.username
            valueFrom:
              secretKeyRef:
                key: username
                name: zendesk-integration
          - name: fint.zendesk.token
            valueFrom:
              secretKeyRef:
                key: token
                name: zendesk-integration
