springfox:
  title: 'FINT Kunde Portal API'
  version: '@version@'

fint:
  identity:
    rotate:
      cron: '0 0 0 * * *' # every midnight
  ldap:
    url: "${url}"
    user: "${user}"
    password: "${password}"
    component-base: "ou=apis,o=fint-test"
    organisation-base: "ou=organisations,o=fint-test"
    contact-base: "ou=contacts,o=fint-test"
  portal:
    admin:
      uri: https://admin-beta.fintlabs.no
  customer:
    portal:
      roles:
        -
          name: Admin
          id: ROLE_ADMIN
          description: Full administrator
          #uri:
        -
          name: Adapter
          id: ROLE_ADAPTER
          description: Gir tilgang til å håndtere adapter
          uri: /api/adapters/
        -
          name: Klient
          id: ROLE_CLIENT
          description: Gir tilgang til å håndtere klienter
          uri: /api/clients/
#        -
#          name: Kontakter
#          id: ROLE_CONTACT
#          description: Gir tilgang til å håndtere kontakter
#          uri: /api/contacts/
        -
          name: Komponenter
          id: ROLE_COMPONENT
          description: Gir tilgang til å håndtere komponenter
          uri: /api/components/organisation/
        -
          name: Tilgangspakker
          id: ROLE_ACCESS_PACKAGE
          description: Gir tilgang til å håndtere tilgangspakker
          uri: /api/access/
#        -
#          name: Brukerhjelp
#          id: ROLE_SUPPORT
#          description: Gir tilgang til å sende inn supportsaker
#        -
#          name: Test
#          id: ROLE_TEST
#          description: Gir tilgang til å kjøre tester
        -
          name: Log
          id: ROLE_LOG
          description: Gir tilgang til å se logger
          uri: /api/events/api/
        -
          name: Assets
          id: ROLE_ASSETS
          description: Gir tilgang til å håndtere assets
          uri: /api/assets/

info:
  app:
    name: FINT Kunde Portal
    description: Portal for å administrere tilganger til FINT
    version: 1.0.0

management:
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: 'true'
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: 'full'


spring:
  cache:
    cache-names: users
    type: caffeine
    caffeine:
      spec: expireAfterWrite=5m
  application:
    name: "fint-kunde-portal"

