springfox:
  title: 'FINT Kunde Portal API'
  version: '@version@'

fint:
  identity:
    rotate:
      cron: '0 0 0 * * *' # every midnight
  ldap:
    url: "${url}"
    user: "${user}"
    password: "${password}"
    component-base: "ou=apis,o=fint-test"
    organisation-base: "ou=organisations,o=fint-test"
    contact-base: "ou=contacts,o=fint-test"
  portal:
    admin:
      uri: https://admin-beta.fintlabs.no
  customer:
    portal:
      roles:
        -
          name: Admin
          id: ROLE_ADMIN
          description: Full administrator
          #uri:
        -
          name: Adapter
          id: ROLE_ADAPTER
          description: Kan håndtere adapter
          uri: /api/adapters/
        -
          name: Klient
          id: ROLE_CLIENT
          description: Kan håndtere klienter
          uri: /api/clients/
        -
          name: Komponenter
          id: ROLE_COMPONENT
          description: Kan håndtere komponenter
          uri: /api/components/organisation/
        -
          name: Tilgangspakker
          id: ROLE_ACCESS_PACKAGE
          description: Kan håndtere tilgangspakker
          uri: /api/accesses/
        -
          name: Brukerhjelp
          id: ROLE_SUPPORT
          description: Kan sende inn supportsaker
          uri: /api/tickets/
        -
          name: Test
          id: ROLE_TEST
          description: Kan kjøre tester
          uri: /api/tests/
        -
          name: Log
          id: ROLE_LOG
          description: Kan se logger
          uri: /api/events/
        -
          name: Assets
          id: ROLE_ASSET
          description: Kan håndtere assets
          uri: /api/assets/
        -
          name: Organisasjon
          id: ROLE_ORGANISATION
          description: Kan håndtere organisasjonen
          uri: /api/organisations/

info:
  app:
    name: FINT Kunde Portal
    description: Portal for å administrere tilganger til FINT
    version: 1.0.0

management:
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: 'true'
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: 'full'


spring:
  cache:
    cache-names:
      - users
      - assetIds
    type: caffeine
    caffeine:
      spec: expireAfterWrite=5m
  application:
    name: "fint-kunde-portal"
