export const LOAD_ADAPTERS_SUCCESS = 'LOAD_ADAPTERS_SUCCESS';
export const UPDATE_ADAPTER_SUCCESS = 'UPDATE_ADAPTER_SUCCESS';
export const CREATE_ADAPTER_SUCCESS = 'CREATE_ADAPTER_SUCCESS';
export const DELETE_ADAPTER_SUCCESS = 'DELETE_ADAPTER_SUCCESS';