export const LOAD_ADAPTERS_SUCCESS = 'LOAD_ADAPTERS_SUCCESS';
export const UPDATE_ADAPTER_SUCCESS = 'UPDATE_ADAPTER_SUCCESS';
export const CREATE_ADAPTER_SUCCESS = 'CREATE_ADAPTER_SUCCESS';
export const DELETE_ADAPTER_SUCCESS = 'DELETE_ADAPTER_SUCCESS';
export const LOAD_KONTAKTER_SUCCESS = 'LOAD_KONTAKTER_SUCCESS';
export const UPDATE_KONTAKTER_SUCCESS = 'UPDATE_KONTAKTER_SUCCESS';
export const CREATE_KONTAKTER_SUCCESS = 'CREATE_KONTAKTER_SUCCESS';
export const DELETE_KONTAKTER_SUCCESS = 'DELETE_KONTAKTER_SUCCESS';

