apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kunde-portal-backend
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-kunde-portal-backend
    app.kubernetes.io/instance: fint-kunde-portal-backend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kunde-portal-backend:latest
  onePassword:
    itemPath: vaults/aks-beta-vault/items/kunde-portal
  envFrom:
    - secretRef:
        name: fint-portal-user
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1800M'
    - name: 'fint.portal.tests.test-runner'
      value: 'http://fint-test-runner:8080'
  resources:
    limits:
      memory: "2Gi"
      cpu: "1"
    requests:
      memory: "1Gi"
      cpu: "250m"