name: CD

on:
  repository_dispatch:
    types: [trigger-cd]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
<<<<<<< HEAD
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
=======
        uses: actions/checkout@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
>>>>>>> efc2afc (add kustomize & add CI/CD)
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
<<<<<<< HEAD
        uses: docker/metadata-action@v5
=======
        uses: docker/metadata-action@v4.3.0
>>>>>>> efc2afc (add kustomize & add CI/CD)
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
            latest

      - name: Build and push Docker image
<<<<<<< HEAD
        uses: docker/build-push-action@v5
=======
        uses: docker/build-push-action@v4
>>>>>>> efc2afc (add kustomize & add CI/CD)
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-aks:
    name: deploy for ${{ matrix.org }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        org:
          - fintlabs-no
        cluster:
#          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
#          - aks-api-fint-2022-02-08
#          - aks-pwf-fint-2021-10-20

    steps:
      - name: Checkout repository
<<<<<<< HEAD
        uses: actions/checkout@v4
=======
        uses: actions/checkout@v3.3.0
>>>>>>> efc2afc (add kustomize & add CI/CD)

      - name: Get environment
        uses: actions/github-script@v6
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1]
          result-encoding: string

      - name: Get resource group name
        uses: actions/github-script@v6
        id: resource-group
        with:
          script: return 'rg-aks-${{ steps.environment.outputs.result }}'
          result-encoding: string

      - name: Bake manifests with Kustomize
        id: bake
<<<<<<< HEAD
        uses: azure/k8s-bake@v2
=======
        uses: azure/k8s-bake@v2.4
>>>>>>> efc2afc (add kustomize & add CI/CD)
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ steps.environment.outputs.result }}'

<<<<<<< HEAD
      - uses: azure/login@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"

      - uses: azure/use-kubelogin@v1.1
        with:
          kubelogin-version: 'v0.0.26'

      - name: Set the target cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: '${{ matrix.cluster }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'
          admin: 'true'
          use-kubelogin: 'true'
=======
      - name: Set the target cluster
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"
          cluster-name: '${{ matrix.cluster }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'
>>>>>>> efc2afc (add kustomize & add CI/CD)

      - name: Deploy
        uses: azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build-and-push.outputs.tags }}
          namespace: ${{ matrix.org }}
